### ISSUE TITLE
Feature Request - Display `value` in schema validation error (regex, codeList)

### ISSUE THREAD

**Issue by mauroz77** [overture-stack/js-lectern-client#28]
## Detailed Description

When the value of a field in a schema is invalid, the resulting JSON shows details about the error. In some cases, the `info` property contains the field's value but in other cases, like _regex_ and _codeList_, it’s empty.

Specifically, for _regex_ and _codeList_ validations, the `value` attribute is only added when in the schema the field was defined as `isArray: true`.

It’d be useful to return the value that didn’t pass the validation to offer more information for the user to fix the error.

## Possible Implementation

Modify _regex_ and _codeList_ validation functions in `src/schema-functions.ts` to include any value or values that are invalid, regardless of the field being `isArray`.

Additionally, for _codeList_ the info object could have a new attribute, `allowedValues`, which holds a list of strings with the allowed values defined for the field, so the user can clearly see why the value didn’t pass the validation.
Example:

```
{
   "errorType":"INVALID_ENUM_VALUE",
   "index":0,
   "fieldName":"string_with_code_list",
   "info":{
      "value":[
         "Fourth"
      ],
      "allowedValues":[
         "First",
         "Second",
         "Third",
         "Other"
      ]
   },
   "message":"The value is not permissible for this field."
}
```
The reason I'm proposing the list of allowed values as an additional property in `info` as opposed to including it in the `message` property is to not impact clients of this code who might expect the value in `message` as just the text it currently is. And by putting this data as an additional field, it's up to the clients to use it or not.

**Comment by joneubank** [comment]
I like the idea of adding in details of the restriction that failed to validate, ie. showing the `allowedValues` list. I would suggest we also show the `regex` pattern when that fails to match.

My one concern with this, how do we want to handle the case where the allowed values list is very long. There are already cases where the code list is hundreds of elements long (we have nearly 1000 options in the `adverse_events` property of the `treatment` schema in [ICGC Argo Dictionary](https://docs.icgc-argo.org/dictionary). Would you shorten the list in cases where the list is greater than 10 items? If we don't handle this then I fear the error messages would be more cumbersome with the values that without.

One alternative approach to including the restriction details in the error message would be to provide a link in the message that would go to the schema details of the field.  We would need to create a new endpoint to support this, but the end result would be a URL that would return all the details for the field that was in error. The URL would have to include the dictionary ID, schema name, and field name to get the needed details. If you like this approach more, we can create another ticket for that functionality and then add the URL to the error messages.

**Comment by mauroz77** [comment]
The `regex` pattern is already shown in the error object so it only the `value` is missing:
```
{
   "errorType":"INVALID_BY_REGEX",
   "index":0,
   "fieldName":"string_with_regex",
   "info":{
      "regex":"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)+$"
   },
   "message":"The value is not a permissible for this field, it must meet the regular expression: \"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)+$\"."
}
```
Regarding the number of elements in `allowedValues`, yes having many elements in the allowed values list would be cumbersome. I like the idea of shortening it up to 10 elements because in the _pdcm_ use case, it'd cover probably most scenarios, and when it doesn't, it'd help at least as an example of the valid values. I also see how adding a link referencing the `dictionary#schema#field` would be useful. Maybe we can use both strategies?

If using a shortened list of allowed values, do you think showing the list with an "..." at the end would be clear enough to inform that there are more values? Something like: "allowedValues": ["First", "Second", ...]

**Comment by joneubank** [comment]
Resolved. Thanks @mauroz77
